apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vishwanginx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Vishwanathms/nginx-helm-argocd.git
    targetRevision: main
    path: .     # repo-relative path

  destination:
    server: https://kubernetes.default.svc
    namespace: u16

  syncPolicy:
    automated:
      prune: true        # deletes removed resources
      selfHeal: true     # reverts manual kubectl changes
    syncOptions:
      - CreateNamespace=true
